Gfo 13
green-fox-academy/giggle-foxticket-opal-fullstack pull request #42
Opened 2020-08-23 18:22 UTC by LLaszlo89

Well let's get started.

2020-08-23 19:42 UTC, marcianszlovak commented on backend/migrations/20200808174929-Orders.js
> +};
Rename file to Order so naming is singular like Ticket?

2020-08-27 16:03 UTC, adamgyulavari requested changes

2020-08-27 16:03 UTC, adamgyulavari commented on backend/test/authenticate.test.js
> +    expect(resp.status).toBe(401);
@LLaszlo89 
- here you don't need to mock the `next` that won't be used, you can just pass a `null`
- `resp` on the other hand need to contain a `status()` that will be _called_ and that should be checked
- also the thing that `status()` is returning should have a `json()` that will be _called_ and that also should be checked

2020-08-27 16:03 UTC, adamgyulavari commented on backend/test/session.test.js
> +      .send(InvalideUser)
@LLaszlo89 either fix the spelling and variable names start with lowerCase letters or just put here the object

2020-08-27 16:03 UTC, adamgyulavari commented on backend/test/session.test.js
> +      .send(ValideUser)
@LLaszlo89 same here

2020-08-27 16:03 UTC, adamgyulavari commented on backend/test/subscription.test.js
> +jest.mock('../src/services/UserService');
@LLaszlo89 remove the space at the end

2020-08-27 16:03 UTC, adamgyulavari commented on backend/test/subscription.test.js
> +
@LLaszlo89 empty line

2020-09-01 13:11 UTC, adamgyulavari requested changes

2020-09-01 13:11 UTC, adamgyulavari commented on backend/src/repository/TicketTypesRepository.js
> +      `INSERT INTO ${this.db}.TicketTypes (name, price, description, icon)
@LLaszlo89 just leave out the db:
```suggestion
      `INSERT INTO TicketTypes (name, price, description, icon)
```

2020-09-01 13:11 UTC, adamgyulavari commented on backend/src/seed.js
> +userRepo.saveAdmin({
@LLaszlo89 ugh, I've missed this :)
we should have only one method for saving the user, the difference is the user object (that can be admin or not admin shouldn't matter)

2020-09-01 17:05 UTC, adamgyulavari approved these changes

2020-09-01 17:06 UTC, merged