GFO-48: Displaying tickets with their QR codes after downloading them from backend and adding into store
green-fox-academy/giggle-foxticket-opal-fullstack pull request #52
Opened 2020-09-21 10:13 UTC by tamas-w

2020-09-22 08:00 UTC, adamgyulavari requested changes

2020-09-22 08:00 UTC, adamgyulavari commented on frontend/src/components/UserTicketList/UserTicketList.jsx
> +export default connect(mapStateToProps, mapDispatchToProps)(UserTicketList);
@tamas-w empty line

2020-09-22 08:00 UTC, adamgyulavari commented on frontend/src/flux/reducers/ticketReducer.js
> +      return{
```suggestion
      return {
```

2020-09-23 20:03 UTC, adamgyulavari approved these changes

2020-09-23 20:09 UTC, adamgyulavari requested changes

2020-09-23 20:09 UTC, adamgyulavari commented on frontend/src/components/UserTicketList/UserTicketList.jsx
> +      {tickets[0] &&
```suggestion
      {tickets.length > 0 && 
```

2020-09-24 13:32 UTC, marcianszlovak approved these changes

2020-09-24 13:53 UTC, marcianszlovak approved these changes

2020-09-24 13:54 UTC, marcianszlovak approved these changes

2020-09-24 13:56 UTC, marcianszlovak approved these changes
approved!

2020-09-24 14:21 UTC, adamgyulavari approved these changes
sadly I was the one who requested the changes, so I have to approve :D

2020-09-24 16:45 UTC, merged